# 连接外网可以访问的数据库
version: "3.8"

services: # 一个services 下面包含多个项目服务
  web:  # 服务1
    build: # 使用当前目录下的Dockerfile进行构建,build也可以指定文件路径，Dockerfile的名字.
      context: .
      dockerfile: Dockerfile
    container_name: docker-gs-ping # 容器名称
    hostname: docker-gs-ping  # 设置hostname 在同一子网内，可以互相用hostname访问
    image: docker-gs-ping:v1.0.0 # 指定生成镜像的 名称:标签
    env_file: # 从指定文件中获取环境变量
      - ./db.env
    networks:
      - mynet
    ports:
      - 8080:8080
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGDATABASE=${PGDATABASE:-apaas}
    deploy: # 重新启动策略
      restart_policy:
        condition: on-failure # on-failure 在容器非正常退出时（退出状态非0），才会重启容器

networks:
  mynet:
    driver: bridge  # 创建的网络时候需要指定driver（单一网络使用bridge，swarm集群使用overlay），而且driver内容不能省略