# 连接外网可以访问的数据库
version: "3.8"

services: # 一个services 下面包含多个项目服务
  web:  # 服务1
    build: # 使用当前目录下的Dockerfile进行构建,build也可以指定文件路径，Dockerfile的名字.
      context: .
      dockerfile: dev.Dockerfile
    container_name: docker-gs-ping # 容器名称
    hostname: docker-gs-ping  # 设置hostname 在同一子网内，可以互相用hostname访问
    image: app:v1.0.1 # 指定生成镜像的 名称:标签
    env_file: # 从指定文件中获取环境变量
      - db.env
    networks:
      - mynet
    ports:
      - 8080:8080
    logging:
      driver: json-file    # 容器的日志: /var/lib/docker/containers/$containerId/
      options:
        max-size: "20M" # 单个文件大小为20M,超过了会创建新的文件
        max-file: "10" # 最多10个文件,当达到文件限制上限，会自动删除旧的文件。
    deploy: # 重新启动策略
      restart_policy:
        condition: on-failure # on-failure 在容器非正常退出时（退出状态非0），才会重启容器

networks:
  mynet:
    driver: bridge  # 创建的网络时候需要指定driver（单一网络使用bridge，swarm集群使用overlay），而且driver内容不能省略